version: '3.8'

services:
  autosummary:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: autosummary-app
    ports:
      - "8501:8501"
    environment:
      # Chrome options for container environment
      - CHROME_OPTIONS=--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222
      # Streamlit configuration
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    volumes:
      # Persist story data and summaries
      - ./story:/app/story
      - ./summary:/app/summary
      - ./crawl_history.json:/app/crawl_history.json
    restart: unless-stopped
    # Add shared memory size for Chrome
    shm_size: 2g
    # Security options
    security_opt:
      - seccomp:unconfined
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: autosummary-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates if needed
      # - ./certs:/etc/nginx/certs:ro
    depends_on:
      - autosummary
    profiles:
      - production
    restart: unless-stopped

networks:
  default:
    name: autosummary-network
